---

- name: Delete all PostgreSQL databases
  become_user: "{{ db_is_remote and 'ansible' or 'postgres' }}"
  hosts:
    - shard_dbs
  tasks:
    - name: Check wipe_environment_enabled has been set to True
      assert:
        that: "{{ wipe_environment_enabled|default(False) }} == True"
        fail_msg: 'This playbook will delete all data. To continue, set
          "wipe_environment_enabled: True" in public.yml. Take care to unset
          "wipe_environment_enabled" when the environment setup is complete.'

    - name: Drop PostgreSQL databases
      become_user: "{{ db_is_remote and 'ansible' or 'postgres' }}"
      vars:
        ansible_ssh_pipelining: true
      with_items: "{{ postgresql_dbs.all }}"
      # Only delete the databases we created (standby DB is not created, and not deleted)
      when: item.create and ((item.host == postgresql_host) or is_monolith|bool)
      postgresql_db:
        name: "{{ item.name }}"
        state: absent
        port: "{{ postgresql_port }}"
        login_host: "{{ db_is_remote and postgresql_host or omit }}"
        login_user: "{{ db_is_remote and postgres_users.root.username or omit }}"
        login_password: "{{ db_is_remote and postgres_users.root.password or omit }}"
